"""
ffdl.protocol - Windows Custom Protocol Handler & Deep Link Parser
==================================================================
Manages `ffdl://` protocol registration in the Windows Registry (HKCU)
and parses deep-link URIs generated by the browser extension.

URI Format:
    ffdl://download?url=<target_url>&hoster=<fuckingfast|datanodes|filekeeper|magnet>&main_only=<1|0>&out=<dir>
"""

from __future__ import annotations

import os
import sys
import urllib.parse
from pathlib import Path
from typing import Any, Dict, Optional


PROTOCOL_SCHEME = "ffdl"
DEFAULT_DAEMON_PORT = 45732


def parse_protocol_url(uri: str) -> Dict[str, Any]:
    """
    Parses an `ffdl://` protocol deep link into structured CLI arguments.
    Example:
        ffdl://download?url=https%3A%2F%2Ffitgirl-repacks.site%2Fgame%2F&hoster=fuckingfast&main_only=1
    """
    clean_uri = uri.strip()
    if clean_uri.lower().startswith(f"{PROTOCOL_SCHEME}://"):
        remainder = clean_uri[len(f"{PROTOCOL_SCHEME}://"):]
    elif clean_uri.lower().startswith(f"{PROTOCOL_SCHEME}:"):
        remainder = clean_uri[len(f"{PROTOCOL_SCHEME}:"):]
    else:
        remainder = clean_uri

    remainder = remainder.lstrip("/")
    endpoint = remainder.split("?")[0].rstrip("/")
    query_str = remainder.split("?", 1)[1] if "?" in remainder else ""

    params = urllib.parse.parse_qs(query_str)

    target_url = params.get("url", [""])[0]
    hoster = params.get("hoster", [""])[0].lower()
    main_only = params.get("main_only", ["0"])[0] in ("1", "true", "yes")
    all_parts = params.get("all", ["0"])[0] in ("1", "true", "yes")
    select = params.get("select", [""])[0]
    out_dir = params.get("out", [""])[0]

    return {
        "action": endpoint or "download",
        "url": target_url,
        "hoster": hoster,
        "main_only": main_only,
        "all_parts": all_parts,
        "select": select,
        "out_dir": out_dir,
        "raw_uri": uri,
    }


def build_protocol_url(
    url: str,
    hoster: str = "",
    main_only: bool = False,
    all_parts: bool = False,
    select: str = "",
    out_dir: str = "",
) -> str:
    """Builds a valid `ffdl://` deep link string."""
    params: Dict[str, str] = {"url": url}
    if hoster:
        params["hoster"] = hoster
    if main_only:
        params["main_only"] = "1"
    if all_parts:
        params["all"] = "1"
    if select:
        params["select"] = select
    if out_dir:
        params["out"] = out_dir

    return f"{PROTOCOL_SCHEME}://download?{urllib.parse.urlencode(params)}"


def get_protocol_launcher_path() -> Path:
    """Returns the path to the ffdl batch runner script in ~/.ffdl/ffdl-run.bat."""
    ffdl_dir = Path.home() / ".ffdl"
    ffdl_dir.mkdir(parents=True, exist_ok=True)
    return ffdl_dir / "ffdl-run.bat"


def write_protocol_launcher_script(python_exe: str) -> Path:
    """
    Generates a dedicated, bulletproof Windows batch runner.
    This avoids CMD nested quote mangling, preserves ampersands in query strings,
    switches to the user's Downloads directory, and keeps the terminal window open.
    """
    bat_path = get_protocol_launcher_path()
    bat_content = (
        "@echo off\r\n"
        "title FFDL - FitGirl Download Accelerator\r\n"
        "setlocal enabledelayedexpansion\r\n\r\n"
        ":: Automatically switch to the user's Downloads folder\r\n"
        'cd /d "%USERPROFILE%\\Downloads" 2>nul || cd /d "%USERPROFILE%"\r\n\r\n'
        f'"{python_exe}" -m ffdl %*\r\n\r\n'
        "if %errorlevel% neq 0 (\r\n"
        "    echo.\r\n"
        "    echo =====================================================================\r\n"
        "    echo [FFDL Error] Download accelerator exited with error code %errorlevel%.\r\n"
        ")\r\n\r\n"
        "echo.\r\n"
        "echo =====================================================================\r\n"
        "echo [FFDL] Finished. Window will remain open for your review.\r\n"
        "echo Press any key to close this window...\r\n"
        "pause >nul\r\n"
    )
    bat_path.write_text(bat_content, encoding="utf-8")
    return bat_path


def register_windows_protocol(python_exe: Optional[str] = None) -> bool:
    """
    Registers the `ffdl://` protocol in Windows Current User Registry (HKCU).
    Directly invokes python executable in a persistent console window,
    avoiding any cmd.exe shell quoting, ampersand splitting, or path errors.
    Requires NO administrator privileges.
    """
    if sys.platform != "win32":
        return False

    try:
        import winreg
        import ctypes

        py_raw = python_exe or sys.executable
        buf = ctypes.create_unicode_buffer(1024)
        ctypes.windll.kernel32.GetShortPathNameW(py_raw, buf, 1024)
        py_short = buf.value if buf.value else py_raw

        command_str = f'"{py_short}" -m ffdl "%1"'

        # Key: HKCU\Software\Classes\ffdl
        base_key_path = f"Software\\Classes\\{PROTOCOL_SCHEME}"
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER, base_key_path) as key:
            winreg.SetValueEx(key, "", 0, winreg.REG_SZ, "URL:FFDL Protocol")
            winreg.SetValueEx(key, "URL Protocol", 0, winreg.REG_SZ, "")

        # Key: HKCU\Software\Classes\ffdl\shell\open\command
        cmd_key_path = f"{base_key_path}\\shell\\open\\command"
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER, cmd_key_path) as cmd_key:
            winreg.SetValueEx(cmd_key, "", 0, winreg.REG_SZ, command_str)

        return True
    except Exception:
        return False


def unregister_windows_protocol() -> bool:
    """Removes the `ffdl://` protocol from Windows Registry."""
    if sys.platform != "win32":
        return False

    try:
        import winreg

        def delete_subkeys(key, subkey_path):
            try:
                with winreg.OpenKey(key, subkey_path, 0, winreg.KEY_ALL_ACCESS) as sub_key:
                    while True:
                        try:
                            sub_name = winreg.EnumKey(sub_key, 0)
                            delete_subkeys(key, f"{subkey_path}\\{sub_name}")
                        except OSError:
                            break
                winreg.DeleteKey(key, subkey_path)
            except FileNotFoundError:
                pass

        delete_subkeys(winreg.HKEY_CURRENT_USER, f"Software\\Classes\\{PROTOCOL_SCHEME}")
        return True
    except Exception:
        return False


def is_windows_protocol_registered() -> bool:
    """Checks if `ffdl://` protocol is currently registered in Windows HKCU."""
    if sys.platform != "win32":
        return False

    try:
        import winreg

        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, f"Software\\Classes\\{PROTOCOL_SCHEME}\\shell\\open\\command") as key:
            val, _ = winreg.QueryValueEx(key, "")
            return bool(val and "ffdl" in val)
    except Exception:
        return False
